# This is a basic workflow to help you get started with Actions

name: CI

on:
  repository_dispatch:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: download
        run: wget -O config.yaml https://feed.iggapis.net/c/303e862c-3286-4d71-a139-f4918e479aad/platform/clash/iGG-iGuge
      
      - name: Commit
        run: |
          git add config.yaml
          git commit -m "[$(LANG=C date)] auto update" || exit 0
          [ -n "${{ secrets.READ_ONLY }}" ] && git show && exit 0
          git push origin master
