name: Auto update

on:
  schedule:
    - cron: '0 12 * * *'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: iGuge Clash Config
      run: wget -O config.yaml https://feed.iggapis.net/c/303e862c-3286-4d71-a139-f4918e479aad/platform/clash/iGG-iGuge
